[package]
name = "swagger"
version = "1.0.0"
authors = ["Swagger Codegen team and contributors"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.9"
serde_json = "1.0"
base64 = "0.21.0"
futures = "0.3"
hyper = "0.14"
url = "2.3.1"

[dev-dependencies]
tokio-core = "*"
