/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.17
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// GetCorporationsCorporationIdDivisionsOk : 200 ok object

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GetCorporationsCorporationIdDivisionsOk {
  /// hangar array
  #[serde(rename = "hangar")]
  hangar: Option<Vec<::models::GetCorporationsCorporationIdDivisionsHangarHangar>>,
  /// wallet array
  #[serde(rename = "wallet")]
  wallet: Option<Vec<::models::GetCorporationsCorporationIdDivisionsWalletWallet>>
}

impl GetCorporationsCorporationIdDivisionsOk {
  /// 200 ok object
  pub fn new() -> GetCorporationsCorporationIdDivisionsOk {
    GetCorporationsCorporationIdDivisionsOk {
      hangar: None,
      wallet: None
    }
  }

  pub fn set_hangar(&mut self, hangar: Vec<::models::GetCorporationsCorporationIdDivisionsHangarHangar>) {
    self.hangar = Some(hangar);
  }

  pub fn with_hangar(mut self, hangar: Vec<::models::GetCorporationsCorporationIdDivisionsHangarHangar>) -> GetCorporationsCorporationIdDivisionsOk {
    self.hangar = Some(hangar);
    self
  }

  pub fn hangar(&self) -> Option<&Vec<::models::GetCorporationsCorporationIdDivisionsHangarHangar>> {
    self.hangar.as_ref()
  }

  pub fn reset_hangar(&mut self) {
    self.hangar = None;
  }

  pub fn set_wallet(&mut self, wallet: Vec<::models::GetCorporationsCorporationIdDivisionsWalletWallet>) {
    self.wallet = Some(wallet);
  }

  pub fn with_wallet(mut self, wallet: Vec<::models::GetCorporationsCorporationIdDivisionsWalletWallet>) -> GetCorporationsCorporationIdDivisionsOk {
    self.wallet = Some(wallet);
    self
  }

  pub fn wallet(&self) -> Option<&Vec<::models::GetCorporationsCorporationIdDivisionsWalletWallet>> {
    self.wallet.as_ref()
  }

  pub fn reset_wallet(&mut self) {
    self.wallet = None;
  }

}



