/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.17
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// GetFwLeaderboardsKills : Top 4 rankings of factions by number of kills from yesterday, last week and in total

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GetFwLeaderboardsKills {
  /// Top 4 ranking of factions active in faction warfare by total kills. A faction is considered \"active\" if they have participated in faction warfare in the past 14 days
  #[serde(rename = "active_total")]
  active_total: Vec<::models::GetFwLeaderboardsActiveTotalActiveTotal>,
  /// Top 4 ranking of factions by kills in the past week
  #[serde(rename = "last_week")]
  last_week: Vec<::models::GetFwLeaderboardsLastWeekLastWeek>,
  /// Top 4 ranking of factions by kills in the past day
  #[serde(rename = "yesterday")]
  yesterday: Vec<::models::GetFwLeaderboardsYesterdayYesterday>
}

impl GetFwLeaderboardsKills {
  /// Top 4 rankings of factions by number of kills from yesterday, last week and in total
  pub fn new(active_total: Vec<::models::GetFwLeaderboardsActiveTotalActiveTotal>, last_week: Vec<::models::GetFwLeaderboardsLastWeekLastWeek>, yesterday: Vec<::models::GetFwLeaderboardsYesterdayYesterday>) -> GetFwLeaderboardsKills {
    GetFwLeaderboardsKills {
      active_total: active_total,
      last_week: last_week,
      yesterday: yesterday
    }
  }

  pub fn set_active_total(&mut self, active_total: Vec<::models::GetFwLeaderboardsActiveTotalActiveTotal>) {
    self.active_total = active_total;
  }

  pub fn with_active_total(mut self, active_total: Vec<::models::GetFwLeaderboardsActiveTotalActiveTotal>) -> GetFwLeaderboardsKills {
    self.active_total = active_total;
    self
  }

  pub fn active_total(&self) -> &Vec<::models::GetFwLeaderboardsActiveTotalActiveTotal> {
    &self.active_total
  }


  pub fn set_last_week(&mut self, last_week: Vec<::models::GetFwLeaderboardsLastWeekLastWeek>) {
    self.last_week = last_week;
  }

  pub fn with_last_week(mut self, last_week: Vec<::models::GetFwLeaderboardsLastWeekLastWeek>) -> GetFwLeaderboardsKills {
    self.last_week = last_week;
    self
  }

  pub fn last_week(&self) -> &Vec<::models::GetFwLeaderboardsLastWeekLastWeek> {
    &self.last_week
  }


  pub fn set_yesterday(&mut self, yesterday: Vec<::models::GetFwLeaderboardsYesterdayYesterday>) {
    self.yesterday = yesterday;
  }

  pub fn with_yesterday(mut self, yesterday: Vec<::models::GetFwLeaderboardsYesterdayYesterday>) -> GetFwLeaderboardsKills {
    self.yesterday = yesterday;
    self
  }

  pub fn yesterday(&self) -> &Vec<::models::GetFwLeaderboardsYesterdayYesterday> {
    &self.yesterday
  }


}



