/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.17
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// GetFwWars200Ok : 200 ok object

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GetFwWars200Ok {
  /// The faction ID of the enemy faction.
  #[serde(rename = "against_id")]
  against_id: i32,
  /// faction_id integer
  #[serde(rename = "faction_id")]
  faction_id: i32
}

impl GetFwWars200Ok {
  /// 200 ok object
  pub fn new(against_id: i32, faction_id: i32) -> GetFwWars200Ok {
    GetFwWars200Ok {
      against_id: against_id,
      faction_id: faction_id
    }
  }

  pub fn set_against_id(&mut self, against_id: i32) {
    self.against_id = against_id;
  }

  pub fn with_against_id(mut self, against_id: i32) -> GetFwWars200Ok {
    self.against_id = against_id;
    self
  }

  pub fn against_id(&self) -> &i32 {
    &self.against_id
  }


  pub fn set_faction_id(&mut self, faction_id: i32) {
    self.faction_id = faction_id;
  }

  pub fn with_faction_id(mut self, faction_id: i32) -> GetFwWars200Ok {
    self.faction_id = faction_id;
    self
  }

  pub fn faction_id(&self) -> &i32 {
    &self.faction_id
  }


}



