/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.17
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// GetCharactersCharacterIdPlanetsPlanetIdLink : link object

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GetCharactersCharacterIdPlanetsPlanetIdLink {
  /// destination_pin_id integer
  #[serde(rename = "destination_pin_id")]
  destination_pin_id: i64,
  /// link_level integer
  #[serde(rename = "link_level")]
  link_level: i32,
  /// source_pin_id integer
  #[serde(rename = "source_pin_id")]
  source_pin_id: i64
}

impl GetCharactersCharacterIdPlanetsPlanetIdLink {
  /// link object
  pub fn new(destination_pin_id: i64, link_level: i32, source_pin_id: i64) -> GetCharactersCharacterIdPlanetsPlanetIdLink {
    GetCharactersCharacterIdPlanetsPlanetIdLink {
      destination_pin_id: destination_pin_id,
      link_level: link_level,
      source_pin_id: source_pin_id
    }
  }

  pub fn set_destination_pin_id(&mut self, destination_pin_id: i64) {
    self.destination_pin_id = destination_pin_id;
  }

  pub fn with_destination_pin_id(mut self, destination_pin_id: i64) -> GetCharactersCharacterIdPlanetsPlanetIdLink {
    self.destination_pin_id = destination_pin_id;
    self
  }

  pub fn destination_pin_id(&self) -> &i64 {
    &self.destination_pin_id
  }


  pub fn set_link_level(&mut self, link_level: i32) {
    self.link_level = link_level;
  }

  pub fn with_link_level(mut self, link_level: i32) -> GetCharactersCharacterIdPlanetsPlanetIdLink {
    self.link_level = link_level;
    self
  }

  pub fn link_level(&self) -> &i32 {
    &self.link_level
  }


  pub fn set_source_pin_id(&mut self, source_pin_id: i64) {
    self.source_pin_id = source_pin_id;
  }

  pub fn with_source_pin_id(mut self, source_pin_id: i64) -> GetCharactersCharacterIdPlanetsPlanetIdLink {
    self.source_pin_id = source_pin_id;
    self
  }

  pub fn source_pin_id(&self) -> &i64 {
    &self.source_pin_id
  }


}



