/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.17
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// GetCorporationsCorporationIdDivisionsHangarHangar : hangar object

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GetCorporationsCorporationIdDivisionsHangarHangar {
  /// division integer
  #[serde(rename = "division")]
  division: Option<i32>,
  /// name string
  #[serde(rename = "name")]
  name: Option<String>
}

impl GetCorporationsCorporationIdDivisionsHangarHangar {
  /// hangar object
  pub fn new() -> GetCorporationsCorporationIdDivisionsHangarHangar {
    GetCorporationsCorporationIdDivisionsHangarHangar {
      division: None,
      name: None
    }
  }

  pub fn set_division(&mut self, division: i32) {
    self.division = Some(division);
  }

  pub fn with_division(mut self, division: i32) -> GetCorporationsCorporationIdDivisionsHangarHangar {
    self.division = Some(division);
    self
  }

  pub fn division(&self) -> Option<&i32> {
    self.division.as_ref()
  }

  pub fn reset_division(&mut self) {
    self.division = None;
  }

  pub fn set_name(&mut self, name: String) {
    self.name = Some(name);
  }

  pub fn with_name(mut self, name: String) -> GetCorporationsCorporationIdDivisionsHangarHangar {
    self.name = Some(name);
    self
  }

  pub fn name(&self) -> Option<&String> {
    self.name.as_ref()
  }

  pub fn reset_name(&mut self) {
    self.name = None;
  }

}



