/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.17
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// GetCorporationsCorporationIdKillmailsRecent200Ok : 200 ok object

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GetCorporationsCorporationIdKillmailsRecent200Ok {
  /// A hash of this killmail
  #[serde(rename = "killmail_hash")]
  killmail_hash: String,
  /// ID of this killmail
  #[serde(rename = "killmail_id")]
  killmail_id: i32
}

impl GetCorporationsCorporationIdKillmailsRecent200Ok {
  /// 200 ok object
  pub fn new(killmail_hash: String, killmail_id: i32) -> GetCorporationsCorporationIdKillmailsRecent200Ok {
    GetCorporationsCorporationIdKillmailsRecent200Ok {
      killmail_hash: killmail_hash,
      killmail_id: killmail_id
    }
  }

  pub fn set_killmail_hash(&mut self, killmail_hash: String) {
    self.killmail_hash = killmail_hash;
  }

  pub fn with_killmail_hash(mut self, killmail_hash: String) -> GetCorporationsCorporationIdKillmailsRecent200Ok {
    self.killmail_hash = killmail_hash;
    self
  }

  pub fn killmail_hash(&self) -> &String {
    &self.killmail_hash
  }


  pub fn set_killmail_id(&mut self, killmail_id: i32) {
    self.killmail_id = killmail_id;
  }

  pub fn with_killmail_id(mut self, killmail_id: i32) -> GetCorporationsCorporationIdKillmailsRecent200Ok {
    self.killmail_id = killmail_id;
    self
  }

  pub fn killmail_id(&self) -> &i32 {
    &self.killmail_id
  }


}



