/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.17
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// GetCharactersCharacterIdLoyaltyPoints200Ok : 200 ok object

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GetCharactersCharacterIdLoyaltyPoints200Ok {
  /// corporation_id integer
  #[serde(rename = "corporation_id")]
  corporation_id: i32,
  /// loyalty_points integer
  #[serde(rename = "loyalty_points")]
  loyalty_points: i32
}

impl GetCharactersCharacterIdLoyaltyPoints200Ok {
  /// 200 ok object
  pub fn new(corporation_id: i32, loyalty_points: i32) -> GetCharactersCharacterIdLoyaltyPoints200Ok {
    GetCharactersCharacterIdLoyaltyPoints200Ok {
      corporation_id: corporation_id,
      loyalty_points: loyalty_points
    }
  }

  pub fn set_corporation_id(&mut self, corporation_id: i32) {
    self.corporation_id = corporation_id;
  }

  pub fn with_corporation_id(mut self, corporation_id: i32) -> GetCharactersCharacterIdLoyaltyPoints200Ok {
    self.corporation_id = corporation_id;
    self
  }

  pub fn corporation_id(&self) -> &i32 {
    &self.corporation_id
  }


  pub fn set_loyalty_points(&mut self, loyalty_points: i32) {
    self.loyalty_points = loyalty_points;
  }

  pub fn with_loyalty_points(mut self, loyalty_points: i32) -> GetCharactersCharacterIdLoyaltyPoints200Ok {
    self.loyalty_points = loyalty_points;
    self
  }

  pub fn loyalty_points(&self) -> &i32 {
    &self.loyalty_points
  }


}



