/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.17
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// GetFwLeaderboardsVictoryPoints : Top 4 rankings of factions by victory points from yesterday, last week and in total

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GetFwLeaderboardsVictoryPoints {
  /// Top 4 ranking of factions active in faction warfare by total victory points. A faction is considered \"active\" if they have participated in faction warfare in the past 14 days
  #[serde(rename = "active_total")]
  active_total: Vec<::models::GetFwLeaderboardsActiveTotalActiveTotal1>,
  /// Top 4 ranking of factions by victory points in the past week
  #[serde(rename = "last_week")]
  last_week: Vec<::models::GetFwLeaderboardsLastWeekLastWeek1>,
  /// Top 4 ranking of factions by victory points in the past day
  #[serde(rename = "yesterday")]
  yesterday: Vec<::models::GetFwLeaderboardsYesterdayYesterday1>
}

impl GetFwLeaderboardsVictoryPoints {
  /// Top 4 rankings of factions by victory points from yesterday, last week and in total
  pub fn new(active_total: Vec<::models::GetFwLeaderboardsActiveTotalActiveTotal1>, last_week: Vec<::models::GetFwLeaderboardsLastWeekLastWeek1>, yesterday: Vec<::models::GetFwLeaderboardsYesterdayYesterday1>) -> GetFwLeaderboardsVictoryPoints {
    GetFwLeaderboardsVictoryPoints {
      active_total: active_total,
      last_week: last_week,
      yesterday: yesterday
    }
  }

  pub fn set_active_total(&mut self, active_total: Vec<::models::GetFwLeaderboardsActiveTotalActiveTotal1>) {
    self.active_total = active_total;
  }

  pub fn with_active_total(mut self, active_total: Vec<::models::GetFwLeaderboardsActiveTotalActiveTotal1>) -> GetFwLeaderboardsVictoryPoints {
    self.active_total = active_total;
    self
  }

  pub fn active_total(&self) -> &Vec<::models::GetFwLeaderboardsActiveTotalActiveTotal1> {
    &self.active_total
  }


  pub fn set_last_week(&mut self, last_week: Vec<::models::GetFwLeaderboardsLastWeekLastWeek1>) {
    self.last_week = last_week;
  }

  pub fn with_last_week(mut self, last_week: Vec<::models::GetFwLeaderboardsLastWeekLastWeek1>) -> GetFwLeaderboardsVictoryPoints {
    self.last_week = last_week;
    self
  }

  pub fn last_week(&self) -> &Vec<::models::GetFwLeaderboardsLastWeekLastWeek1> {
    &self.last_week
  }


  pub fn set_yesterday(&mut self, yesterday: Vec<::models::GetFwLeaderboardsYesterdayYesterday1>) {
    self.yesterday = yesterday;
  }

  pub fn with_yesterday(mut self, yesterday: Vec<::models::GetFwLeaderboardsYesterdayYesterday1>) -> GetFwLeaderboardsVictoryPoints {
    self.yesterday = yesterday;
    self
  }

  pub fn yesterday(&self) -> &Vec<::models::GetFwLeaderboardsYesterdayYesterday1> {
    &self.yesterday
  }


}



