/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.17
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails : factory_details object

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails {
  /// schematic_id integer
  #[serde(rename = "schematic_id")]
  schematic_id: i32
}

impl GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails {
  /// factory_details object
  pub fn new(schematic_id: i32) -> GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails {
    GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails {
      schematic_id: schematic_id
    }
  }

  pub fn set_schematic_id(&mut self, schematic_id: i32) {
    self.schematic_id = schematic_id;
  }

  pub fn with_schematic_id(mut self, schematic_id: i32) -> GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails {
    self.schematic_id = schematic_id;
    self
  }

  pub fn schematic_id(&self) -> &i32 {
    &self.schematic_id
  }


}



