/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.17
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// GetCorporationsCorporationIdMedalsIssued200Ok : 200 ok object

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GetCorporationsCorporationIdMedalsIssued200Ok {
  /// ID of the character who was rewarded this medal
  #[serde(rename = "character_id")]
  character_id: i32,
  /// issued_at string
  #[serde(rename = "issued_at")]
  issued_at: String,
  /// ID of the character who issued the medal
  #[serde(rename = "issuer_id")]
  issuer_id: i32,
  /// medal_id integer
  #[serde(rename = "medal_id")]
  medal_id: i32,
  /// reason string
  #[serde(rename = "reason")]
  reason: String,
  /// status string
  #[serde(rename = "status")]
  status: String
}

impl GetCorporationsCorporationIdMedalsIssued200Ok {
  /// 200 ok object
  pub fn new(character_id: i32, issued_at: String, issuer_id: i32, medal_id: i32, reason: String, status: String) -> GetCorporationsCorporationIdMedalsIssued200Ok {
    GetCorporationsCorporationIdMedalsIssued200Ok {
      character_id: character_id,
      issued_at: issued_at,
      issuer_id: issuer_id,
      medal_id: medal_id,
      reason: reason,
      status: status
    }
  }

  pub fn set_character_id(&mut self, character_id: i32) {
    self.character_id = character_id;
  }

  pub fn with_character_id(mut self, character_id: i32) -> GetCorporationsCorporationIdMedalsIssued200Ok {
    self.character_id = character_id;
    self
  }

  pub fn character_id(&self) -> &i32 {
    &self.character_id
  }


  pub fn set_issued_at(&mut self, issued_at: String) {
    self.issued_at = issued_at;
  }

  pub fn with_issued_at(mut self, issued_at: String) -> GetCorporationsCorporationIdMedalsIssued200Ok {
    self.issued_at = issued_at;
    self
  }

  pub fn issued_at(&self) -> &String {
    &self.issued_at
  }


  pub fn set_issuer_id(&mut self, issuer_id: i32) {
    self.issuer_id = issuer_id;
  }

  pub fn with_issuer_id(mut self, issuer_id: i32) -> GetCorporationsCorporationIdMedalsIssued200Ok {
    self.issuer_id = issuer_id;
    self
  }

  pub fn issuer_id(&self) -> &i32 {
    &self.issuer_id
  }


  pub fn set_medal_id(&mut self, medal_id: i32) {
    self.medal_id = medal_id;
  }

  pub fn with_medal_id(mut self, medal_id: i32) -> GetCorporationsCorporationIdMedalsIssued200Ok {
    self.medal_id = medal_id;
    self
  }

  pub fn medal_id(&self) -> &i32 {
    &self.medal_id
  }


  pub fn set_reason(&mut self, reason: String) {
    self.reason = reason;
  }

  pub fn with_reason(mut self, reason: String) -> GetCorporationsCorporationIdMedalsIssued200Ok {
    self.reason = reason;
    self
  }

  pub fn reason(&self) -> &String {
    &self.reason
  }


  pub fn set_status(&mut self, status: String) {
    self.status = status;
  }

  pub fn with_status(mut self, status: String) -> GetCorporationsCorporationIdMedalsIssued200Ok {
    self.status = status;
    self
  }

  pub fn status(&self) -> &String {
    &self.status
  }


}



