/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.17
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// GetCharactersCharacterIdFittingsItem : item object

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GetCharactersCharacterIdFittingsItem {
  /// flag string
  #[serde(rename = "flag")]
  flag: String,
  /// quantity integer
  #[serde(rename = "quantity")]
  quantity: i32,
  /// type_id integer
  #[serde(rename = "type_id")]
  type_id: i32
}

impl GetCharactersCharacterIdFittingsItem {
  /// item object
  pub fn new(flag: String, quantity: i32, type_id: i32) -> GetCharactersCharacterIdFittingsItem {
    GetCharactersCharacterIdFittingsItem {
      flag: flag,
      quantity: quantity,
      type_id: type_id
    }
  }

  pub fn set_flag(&mut self, flag: String) {
    self.flag = flag;
  }

  pub fn with_flag(mut self, flag: String) -> GetCharactersCharacterIdFittingsItem {
    self.flag = flag;
    self
  }

  pub fn flag(&self) -> &String {
    &self.flag
  }


  pub fn set_quantity(&mut self, quantity: i32) {
    self.quantity = quantity;
  }

  pub fn with_quantity(mut self, quantity: i32) -> GetCharactersCharacterIdFittingsItem {
    self.quantity = quantity;
    self
  }

  pub fn quantity(&self) -> &i32 {
    &self.quantity
  }


  pub fn set_type_id(&mut self, type_id: i32) {
    self.type_id = type_id;
  }

  pub fn with_type_id(mut self, type_id: i32) -> GetCharactersCharacterIdFittingsItem {
    self.type_id = type_id;
    self
  }

  pub fn type_id(&self) -> &i32 {
    &self.type_id
  }


}



