/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.17
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// GetDogmaDynamicItemsTypeIdItemIdOk : 200 ok object

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GetDogmaDynamicItemsTypeIdItemIdOk {
  /// The ID of the character who created the item
  #[serde(rename = "created_by")]
  created_by: i32,
  /// dogma_attributes array
  #[serde(rename = "dogma_attributes")]
  dogma_attributes: Vec<::models::GetDogmaDynamicItemsTypeIdItemIdDogmaAttribute>,
  /// dogma_effects array
  #[serde(rename = "dogma_effects")]
  dogma_effects: Vec<::models::GetDogmaDynamicItemsTypeIdItemIdDogmaEffect>,
  /// The type ID of the mutator used to generate the dynamic item.
  #[serde(rename = "mutator_type_id")]
  mutator_type_id: i32,
  /// The type ID of the source item the mutator was applied to create the dynamic item.
  #[serde(rename = "source_type_id")]
  source_type_id: i32
}

impl GetDogmaDynamicItemsTypeIdItemIdOk {
  /// 200 ok object
  pub fn new(created_by: i32, dogma_attributes: Vec<::models::GetDogmaDynamicItemsTypeIdItemIdDogmaAttribute>, dogma_effects: Vec<::models::GetDogmaDynamicItemsTypeIdItemIdDogmaEffect>, mutator_type_id: i32, source_type_id: i32) -> GetDogmaDynamicItemsTypeIdItemIdOk {
    GetDogmaDynamicItemsTypeIdItemIdOk {
      created_by: created_by,
      dogma_attributes: dogma_attributes,
      dogma_effects: dogma_effects,
      mutator_type_id: mutator_type_id,
      source_type_id: source_type_id
    }
  }

  pub fn set_created_by(&mut self, created_by: i32) {
    self.created_by = created_by;
  }

  pub fn with_created_by(mut self, created_by: i32) -> GetDogmaDynamicItemsTypeIdItemIdOk {
    self.created_by = created_by;
    self
  }

  pub fn created_by(&self) -> &i32 {
    &self.created_by
  }


  pub fn set_dogma_attributes(&mut self, dogma_attributes: Vec<::models::GetDogmaDynamicItemsTypeIdItemIdDogmaAttribute>) {
    self.dogma_attributes = dogma_attributes;
  }

  pub fn with_dogma_attributes(mut self, dogma_attributes: Vec<::models::GetDogmaDynamicItemsTypeIdItemIdDogmaAttribute>) -> GetDogmaDynamicItemsTypeIdItemIdOk {
    self.dogma_attributes = dogma_attributes;
    self
  }

  pub fn dogma_attributes(&self) -> &Vec<::models::GetDogmaDynamicItemsTypeIdItemIdDogmaAttribute> {
    &self.dogma_attributes
  }


  pub fn set_dogma_effects(&mut self, dogma_effects: Vec<::models::GetDogmaDynamicItemsTypeIdItemIdDogmaEffect>) {
    self.dogma_effects = dogma_effects;
  }

  pub fn with_dogma_effects(mut self, dogma_effects: Vec<::models::GetDogmaDynamicItemsTypeIdItemIdDogmaEffect>) -> GetDogmaDynamicItemsTypeIdItemIdOk {
    self.dogma_effects = dogma_effects;
    self
  }

  pub fn dogma_effects(&self) -> &Vec<::models::GetDogmaDynamicItemsTypeIdItemIdDogmaEffect> {
    &self.dogma_effects
  }


  pub fn set_mutator_type_id(&mut self, mutator_type_id: i32) {
    self.mutator_type_id = mutator_type_id;
  }

  pub fn with_mutator_type_id(mut self, mutator_type_id: i32) -> GetDogmaDynamicItemsTypeIdItemIdOk {
    self.mutator_type_id = mutator_type_id;
    self
  }

  pub fn mutator_type_id(&self) -> &i32 {
    &self.mutator_type_id
  }


  pub fn set_source_type_id(&mut self, source_type_id: i32) {
    self.source_type_id = source_type_id;
  }

  pub fn with_source_type_id(mut self, source_type_id: i32) -> GetDogmaDynamicItemsTypeIdItemIdOk {
    self.source_type_id = source_type_id;
    self
  }

  pub fn source_type_id(&self) -> &i32 {
    &self.source_type_id
  }


}



