/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.17
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// GetUniverseSystemKills200Ok : 200 ok object

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GetUniverseSystemKills200Ok {
  /// Number of NPC ships killed in this system
  #[serde(rename = "npc_kills")]
  npc_kills: i32,
  /// Number of pods killed in this system
  #[serde(rename = "pod_kills")]
  pod_kills: i32,
  /// Number of player ships killed in this system
  #[serde(rename = "ship_kills")]
  ship_kills: i32,
  /// system_id integer
  #[serde(rename = "system_id")]
  system_id: i32
}

impl GetUniverseSystemKills200Ok {
  /// 200 ok object
  pub fn new(npc_kills: i32, pod_kills: i32, ship_kills: i32, system_id: i32) -> GetUniverseSystemKills200Ok {
    GetUniverseSystemKills200Ok {
      npc_kills: npc_kills,
      pod_kills: pod_kills,
      ship_kills: ship_kills,
      system_id: system_id
    }
  }

  pub fn set_npc_kills(&mut self, npc_kills: i32) {
    self.npc_kills = npc_kills;
  }

  pub fn with_npc_kills(mut self, npc_kills: i32) -> GetUniverseSystemKills200Ok {
    self.npc_kills = npc_kills;
    self
  }

  pub fn npc_kills(&self) -> &i32 {
    &self.npc_kills
  }


  pub fn set_pod_kills(&mut self, pod_kills: i32) {
    self.pod_kills = pod_kills;
  }

  pub fn with_pod_kills(mut self, pod_kills: i32) -> GetUniverseSystemKills200Ok {
    self.pod_kills = pod_kills;
    self
  }

  pub fn pod_kills(&self) -> &i32 {
    &self.pod_kills
  }


  pub fn set_ship_kills(&mut self, ship_kills: i32) {
    self.ship_kills = ship_kills;
  }

  pub fn with_ship_kills(mut self, ship_kills: i32) -> GetUniverseSystemKills200Ok {
    self.ship_kills = ship_kills;
    self
  }

  pub fn ship_kills(&self) -> &i32 {
    &self.ship_kills
  }


  pub fn set_system_id(&mut self, system_id: i32) {
    self.system_id = system_id;
  }

  pub fn with_system_id(mut self, system_id: i32) -> GetUniverseSystemKills200Ok {
    self.system_id = system_id;
    self
  }

  pub fn system_id(&self) -> &i32 {
    &self.system_id
  }


}



