/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.17
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// GetCharactersCharacterIdCalendarEventIdAttendees200Ok : character_id and response of an attendee

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GetCharactersCharacterIdCalendarEventIdAttendees200Ok {
  /// character_id integer
  #[serde(rename = "character_id")]
  character_id: Option<i32>,
  /// event_response string
  #[serde(rename = "event_response")]
  event_response: Option<String>
}

impl GetCharactersCharacterIdCalendarEventIdAttendees200Ok {
  /// character_id and response of an attendee
  pub fn new() -> GetCharactersCharacterIdCalendarEventIdAttendees200Ok {
    GetCharactersCharacterIdCalendarEventIdAttendees200Ok {
      character_id: None,
      event_response: None
    }
  }

  pub fn set_character_id(&mut self, character_id: i32) {
    self.character_id = Some(character_id);
  }

  pub fn with_character_id(mut self, character_id: i32) -> GetCharactersCharacterIdCalendarEventIdAttendees200Ok {
    self.character_id = Some(character_id);
    self
  }

  pub fn character_id(&self) -> Option<&i32> {
    self.character_id.as_ref()
  }

  pub fn reset_character_id(&mut self) {
    self.character_id = None;
  }

  pub fn set_event_response(&mut self, event_response: String) {
    self.event_response = Some(event_response);
  }

  pub fn with_event_response(mut self, event_response: String) -> GetCharactersCharacterIdCalendarEventIdAttendees200Ok {
    self.event_response = Some(event_response);
    self
  }

  pub fn event_response(&self) -> Option<&String> {
    self.event_response.as_ref()
  }

  pub fn reset_event_response(&mut self) {
    self.event_response = None;
  }

}



