/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.17
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// GetCorporationsCorporationIdBookmarksFolders200Ok : 200 ok object

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GetCorporationsCorporationIdBookmarksFolders200Ok {
  /// creator_id integer
  #[serde(rename = "creator_id")]
  creator_id: Option<i32>,
  /// folder_id integer
  #[serde(rename = "folder_id")]
  folder_id: i32,
  /// name string
  #[serde(rename = "name")]
  name: String
}

impl GetCorporationsCorporationIdBookmarksFolders200Ok {
  /// 200 ok object
  pub fn new(folder_id: i32, name: String) -> GetCorporationsCorporationIdBookmarksFolders200Ok {
    GetCorporationsCorporationIdBookmarksFolders200Ok {
      creator_id: None,
      folder_id: folder_id,
      name: name
    }
  }

  pub fn set_creator_id(&mut self, creator_id: i32) {
    self.creator_id = Some(creator_id);
  }

  pub fn with_creator_id(mut self, creator_id: i32) -> GetCorporationsCorporationIdBookmarksFolders200Ok {
    self.creator_id = Some(creator_id);
    self
  }

  pub fn creator_id(&self) -> Option<&i32> {
    self.creator_id.as_ref()
  }

  pub fn reset_creator_id(&mut self) {
    self.creator_id = None;
  }

  pub fn set_folder_id(&mut self, folder_id: i32) {
    self.folder_id = folder_id;
  }

  pub fn with_folder_id(mut self, folder_id: i32) -> GetCorporationsCorporationIdBookmarksFolders200Ok {
    self.folder_id = folder_id;
    self
  }

  pub fn folder_id(&self) -> &i32 {
    &self.folder_id
  }


  pub fn set_name(&mut self, name: String) {
    self.name = name;
  }

  pub fn with_name(mut self, name: String) -> GetCorporationsCorporationIdBookmarksFolders200Ok {
    self.name = name;
    self
  }

  pub fn name(&self) -> &String {
    &self.name
  }


}



