/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.17
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// GetCharactersCharacterIdShipOk : 200 ok object

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GetCharactersCharacterIdShipOk {
  /// Item id's are unique to a ship and persist until it is repackaged. This value can be used to track repeated uses of a ship, or detect when a pilot changes into a different instance of the same ship type.
  #[serde(rename = "ship_item_id")]
  ship_item_id: i64,
  /// ship_name string
  #[serde(rename = "ship_name")]
  ship_name: String,
  /// ship_type_id integer
  #[serde(rename = "ship_type_id")]
  ship_type_id: i32
}

impl GetCharactersCharacterIdShipOk {
  /// 200 ok object
  pub fn new(ship_item_id: i64, ship_name: String, ship_type_id: i32) -> GetCharactersCharacterIdShipOk {
    GetCharactersCharacterIdShipOk {
      ship_item_id: ship_item_id,
      ship_name: ship_name,
      ship_type_id: ship_type_id
    }
  }

  pub fn set_ship_item_id(&mut self, ship_item_id: i64) {
    self.ship_item_id = ship_item_id;
  }

  pub fn with_ship_item_id(mut self, ship_item_id: i64) -> GetCharactersCharacterIdShipOk {
    self.ship_item_id = ship_item_id;
    self
  }

  pub fn ship_item_id(&self) -> &i64 {
    &self.ship_item_id
  }


  pub fn set_ship_name(&mut self, ship_name: String) {
    self.ship_name = ship_name;
  }

  pub fn with_ship_name(mut self, ship_name: String) -> GetCharactersCharacterIdShipOk {
    self.ship_name = ship_name;
    self
  }

  pub fn ship_name(&self) -> &String {
    &self.ship_name
  }


  pub fn set_ship_type_id(&mut self, ship_type_id: i32) {
    self.ship_type_id = ship_type_id;
  }

  pub fn with_ship_type_id(mut self, ship_type_id: i32) -> GetCharactersCharacterIdShipOk {
    self.ship_type_id = ship_type_id;
    self
  }

  pub fn ship_type_id(&self) -> &i32 {
    &self.ship_type_id
  }


}



