/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.17
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// PostCharactersCharacterIdFittingsFitting : fitting object

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct PostCharactersCharacterIdFittingsFitting {
  /// description string
  #[serde(rename = "description")]
  description: String,
  /// items array
  #[serde(rename = "items")]
  items: Vec<::models::PostCharactersCharacterIdFittingsItem>,
  /// name string
  #[serde(rename = "name")]
  name: String,
  /// ship_type_id integer
  #[serde(rename = "ship_type_id")]
  ship_type_id: i32
}

impl PostCharactersCharacterIdFittingsFitting {
  /// fitting object
  pub fn new(description: String, items: Vec<::models::PostCharactersCharacterIdFittingsItem>, name: String, ship_type_id: i32) -> PostCharactersCharacterIdFittingsFitting {
    PostCharactersCharacterIdFittingsFitting {
      description: description,
      items: items,
      name: name,
      ship_type_id: ship_type_id
    }
  }

  pub fn set_description(&mut self, description: String) {
    self.description = description;
  }

  pub fn with_description(mut self, description: String) -> PostCharactersCharacterIdFittingsFitting {
    self.description = description;
    self
  }

  pub fn description(&self) -> &String {
    &self.description
  }


  pub fn set_items(&mut self, items: Vec<::models::PostCharactersCharacterIdFittingsItem>) {
    self.items = items;
  }

  pub fn with_items(mut self, items: Vec<::models::PostCharactersCharacterIdFittingsItem>) -> PostCharactersCharacterIdFittingsFitting {
    self.items = items;
    self
  }

  pub fn items(&self) -> &Vec<::models::PostCharactersCharacterIdFittingsItem> {
    &self.items
  }


  pub fn set_name(&mut self, name: String) {
    self.name = name;
  }

  pub fn with_name(mut self, name: String) -> PostCharactersCharacterIdFittingsFitting {
    self.name = name;
    self
  }

  pub fn name(&self) -> &String {
    &self.name
  }


  pub fn set_ship_type_id(&mut self, ship_type_id: i32) {
    self.ship_type_id = ship_type_id;
  }

  pub fn with_ship_type_id(mut self, ship_type_id: i32) -> PostCharactersCharacterIdFittingsFitting {
    self.ship_type_id = ship_type_id;
    self
  }

  pub fn ship_type_id(&self) -> &i32 {
    &self.ship_type_id
  }


}



